name: kalshi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  bloc: ^8.1.1
  equatable: ^2.0.7
  injectable: ^2.5.0
  injectable_generator: ^2.6.2
  dio: ^5.7.0
  go_router: ^14.6.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.10
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: work-sans
      fonts:
        - asset: assets/fonts/work-sans-regular.ttf
          weight: 400
        - asset: assets/fonts/work-sans-medium.ttf
          weight: 500
        - asset: assets/fonts/work-sans-semibold.ttf
          weight: 600

    - family: rubik
      fonts:
        - asset: assets/fonts/rubik-medium.ttf
          weight: 500
  assets:
    - assets/images/
    - assets/icons/
  